import XCTest
@testable import AmodalRoadKit

/// Golden values generated by the REAL `predict.py::compose_amodal_mask` +
/// `common.py::occluder_blob_mask` (see GoldenData_AmodalCompose.swift's
/// header) on two synthetic semantic-label scenes -- not just Swift
/// self-consistency. Case 1 (40x50) and case 2 (60x60) both include a
/// vehicle blob touching the road, a person blob that does NOT touch the
/// road (must be excluded even where `ofrsRoad` is true there), and two
/// vehicle blobs touching only diagonally (an 8-connectivity check: they
/// must be treated as ONE component).
final class AmodalComposeGoldenValueTests: XCTestCase {
    func testCase1MatchesPython() {
        runCase(width: 50, height: 40,
               sem: GoldenData.composeCase1Sem,
               ofrsRoad: GoldenData.composeCase1OfrsRoad,
               expectedOcclusionRegion: GoldenData.composeCase1OcclusionRegion,
               expectedPatch: GoldenData.composeCase1Patch,
               expectedFinal: GoldenData.composeCase1Final)
    }

    func testCase2MatchesPython() {
        runCase(width: 60, height: 60,
               sem: GoldenData.composeCase2Sem,
               ofrsRoad: GoldenData.composeCase2OfrsRoad,
               expectedOcclusionRegion: GoldenData.composeCase2OcclusionRegion,
               expectedPatch: GoldenData.composeCase2Patch,
               expectedFinal: GoldenData.composeCase2Final)
    }

    private func runCase(width: Int, height: Int, sem: [Int], ofrsRoad: [Int],
                         expectedOcclusionRegion: [Int], expectedPatch: [Int], expectedFinal: [Int],
                         file: StaticString = #filePath, line: UInt = #line) {
        let semLabels = sem
        let ofrsRoadMask = ofrsRoad.map { $0 == 1 }

        let visible = semLabels.map { $0 == OFRSClasses.roadIdx }
        let occluders = semLabels.map { $0 == OFRSClasses.personIdx || $0 == OFRSClasses.vehicleIdx }
        let occlusionRegion = AmodalCompose.occluderBlobMask(
            occluders: occluders, visible: visible, nearPx: OFRSClasses.roadNeighbourhoodPx,
            width: width, height: height)
        XCTAssertEqual(occlusionRegion.count, expectedOcclusionRegion.count, file: file, line: line)
        for i in 0..<occlusionRegion.count {
            XCTAssertEqual(occlusionRegion[i], expectedOcclusionRegion[i] == 1, "occlusionRegion[\(i)]", file: file, line: line)
        }

        let (final, patch) = AmodalCompose.composeAmodalMask(
            semLabels: semLabels, ofrsRoad: ofrsRoadMask, width: width, height: height)
        for i in 0..<patch.count {
            XCTAssertEqual(patch[i], expectedPatch[i] == 1, "patch[\(i)]", file: file, line: line)
        }
        for i in 0..<final.count {
            XCTAssertEqual(final[i], expectedFinal[i] == 1, "final[\(i)]", file: file, line: line)
        }
    }
}
