import XCTest
@testable import AmodalRoadKit

/// Golden values generated by the REAL `disturbance.attribute` (src/disturbance.py)
/// on a 40x25 synthetic BEV: two vehicle regions (ids 1, 2) plus a region
/// with no seed at all (id 0), exercising the `unattributed` path too, not
/// just the per-vehicle split.
final class AttributionGoldenValueTests: XCTestCase {
    let grid = BevGrid(ppm: 10.0, xMin: -2.0, xMax: 2.0, zMin: 0.5, zMax: 3.0)

    func testAttributeMatchesPython() {
        XCTAssertEqual(grid.width, 40)
        XCTAssertEqual(grid.height, 25)

        var instBev = [Int32](repeating: 0, count: grid.width * grid.height)
        for y in 0..<10 { for x in 0..<15 { instBev[y * grid.width + x] = 1 } }
        for y in 0..<10 { for x in 20..<35 { instBev[y * grid.width + x] = 2 } }

        var occludedBev = [Bool](repeating: false, count: grid.width * grid.height)
        for y in 2..<8 { for x in 2..<12 { occludedBev[y * grid.width + x] = true } }    // inside vehicle 1
        for y in 3..<7 { for x in 22..<30 { occludedBev[y * grid.width + x] = true } }   // inside vehicle 2
        for y in 12..<18 { for x in 5..<20 { occludedBev[y * grid.width + x] = true } }  // inside the id==0 region

        let vehicles = [
            VehicleInstance(instId: 1, label: "vehicle", score: 0.9, pixelArea: 100,
                            centroidU: 0, centroidV: 0, bboxU0: 0, bboxV0: 0, bboxU1: 1, bboxV1: 1,
                            selectable: true, source: "instance"),
            VehicleInstance(instId: 2, label: "vehicle", score: 0.8, pixelArea: 100,
                            centroidU: 0, centroidV: 0, bboxU0: 0, bboxV0: 0, bboxU1: 1, bboxV1: 1,
                            selectable: true, source: "instance"),
        ]

        let (perVehicle, unattributed) = Attribution.attribute(
            occludedBev: occludedBev, instBev: instBev, vehicles: vehicles, grid: grid, scaleFactor: 1.5)

        XCTAssertEqual(occludedBev.filter { $0 }.count, 182)

        XCTAssertEqual(perVehicle[1]?.cells, 60)
        XCTAssertEqual(perVehicle[1]?.areaM2 ?? 0, 0.6, accuracy: 1e-9)
        XCTAssertEqual(perVehicle[1]?.areaM2Raw ?? 0, 0.9, accuracy: 1e-9)

        XCTAssertEqual(perVehicle[2]?.cells, 32)
        XCTAssertEqual(perVehicle[2]?.areaM2 ?? 0, 0.32, accuracy: 1e-9)
        XCTAssertEqual(perVehicle[2]?.areaM2Raw ?? 0, 0.48, accuracy: 1e-9)

        XCTAssertEqual(unattributed.cells, 90)
        XCTAssertEqual(unattributed.areaM2, 0.9, accuracy: 1e-9)
        XCTAssertEqual(unattributed.areaM2Raw, 1.35, accuracy: 1e-9)
    }
}
