import XCTest
import simd
@testable import AmodalRoadKit

/// Golden values generated by the REAL `instances.bottom_contour_points`
/// (src/instances.py) on a 10x8 synthetic mask with two column groups: one
/// whose bottom row sits within 2 rows of the mask's bottom edge (must be
/// excluded as possibly-truncated) and one that does not.
final class BottomContourGoldenValueTests: XCTestCase {
    func testTruncationMatchesPython() {
        let width = 8, height = 10
        var mask = [Bool](repeating: false, count: width * height)
        for y in 3..<9 { for x in 0..<3 { mask[y * width + x] = true } }   // cols 0-2: bottom row 8 (truncated, height-2=8)
        for y in 2..<6 { for x in 4..<7 { mask[y * width + x] = true } }   // cols 4-6: bottom row 5 (usable)

        let (points, coverage) = BottomContour.points(mask: mask, width: width, height: height)
        XCTAssertEqual(points, [SIMD2(4.0, 5.0), SIMD2(5.0, 5.0), SIMD2(6.0, 5.0)])
        XCTAssertEqual(coverage, 0.5, accuracy: 1e-9)
    }

    func testEmptyMaskMatchesPython() {
        let width = 5, height = 5
        let mask = [Bool](repeating: false, count: width * height)
        let (points, coverage) = BottomContour.points(mask: mask, width: width, height: height)
        XCTAssertTrue(points.isEmpty)
        XCTAssertEqual(coverage, 0.0)
    }
}
