import XCTest
@testable import AmodalRoadKit

/// Golden values generated by real `cv2.dilate` + `cv2.getStructuringElement
/// (cv2.MORPH_ELLIPSE, ...)` (see GoldenData_Dilation.swift's header), not
/// just Swift self-consistency -- see GoldenValueTests.swift's header for
/// the overall approach.
final class DilationGoldenValueTests: XCTestCase {
    func testEllipseDilateMatchesOpenCV() {
        let width = 25, height = 21
        let mask = GoldenData.dilationMask.map { $0 == 1 }
        let out = Dilation.dilate(mask: mask, width: width, height: height, radiusPx: 4)
        let expected = GoldenData.dilationOutR4
        XCTAssertEqual(out.count, expected.count)
        for i in 0..<out.count {
            XCTAssertEqual(out[i], expected[i] == 1, "cell \(i)")
        }
    }

    func testZeroRadiusIsIdentity() {
        let width = 5, height = 5
        var mask = [Bool](repeating: false, count: width * height)
        mask[12] = true
        let out = Dilation.dilate(mask: mask, width: width, height: height, radiusPx: 0)
        XCTAssertEqual(out, mask)
    }
}
