import XCTest
@testable import AmodalRoadKit

/// Golden values generated by the REAL `bev.nearest_label_bev` (src/bev.py)
/// via `cv2.distanceTransformWithLabels`, on a 20x29 grid with two small
/// multi-cell seed bands (vehicle 1: 2 cells; vehicle 2: an L-shaped 3-cell
/// band), both with and without a distance cutoff.
final class NearestLabelGoldenValueTests: XCTestCase {
    let grid = BevGrid(ppm: 2.0, xMin: -5.0, xMax: 5.0, zMin: 0.5, zMax: 15.0)

    func makeSeedIds() -> [Int32] {
        var seed = [Int32](repeating: 0, count: grid.width * grid.height)
        seed[5 * grid.width + 3] = 1
        seed[5 * grid.width + 4] = 1
        seed[20 * grid.width + 15] = 2
        seed[20 * grid.width + 16] = 2
        seed[21 * grid.width + 15] = 2
        return seed
    }

    func testNoCutoffMatchesOpenCV() {
        let seed = makeSeedIds()
        let out = NearestLabel.label(seedIds: seed, grid: grid)
        let expected = GoldenData.nearestLabelNoCutoff
        XCTAssertEqual(out.count, expected.count)
        var mismatches = 0
        for i in 0..<out.count where out[i] != expected[i] { mismatches += 1 }
        // Investigated, not just tolerated: the 2 disagreeing cells (out of
        // 580) both sit at near-equidistant boundary points (squared
        // distances 104 vs 106 -- a ~1% difference). cv2.distanceTransformWithLabels
        // uses DIST_MASK_5, an APPROXIMATE distance metric (OpenCV's own docs:
        // "a=1, b=1.4, c=2.1969" for the 5x5 mask, not exact Euclidean), while
        // this Swift implementation computes exact squared distance -- so on
        // an extremely close call, Swift's answer is arguably the more
        // correct one, not a bug to chase. `bev.py`'s own module docstring
        // already documents this ~1% approximation error as acceptable for
        // a Voronoi split plus safety cutoff.
        XCTAssertLessThanOrEqual(mismatches, 2, "\(mismatches)/\(out.count) cells disagree with OpenCV")
    }

    func testWithCutoffMatchesOpenCV() {
        let seed = makeSeedIds()
        let out = NearestLabel.label(seedIds: seed, grid: grid, maxDistM: 3.0)
        let expected = GoldenData.nearestLabelCutoff3m
        XCTAssertEqual(out.count, expected.count)
        var mismatches = 0
        for i in 0..<out.count where out[i] != expected[i] { mismatches += 1 }
        // A distance cutoff creates a hard boundary ring where OpenCV's
        // approximate (DIST_MASK_5) distance and this exact-Euclidean
        // brute-force search can legitimately disagree by a fraction of a
        // pixel right at the threshold -- allow a small boundary margin,
        // unlike the no-cutoff case above which has no such ambiguous edge.
        XCTAssertLessThanOrEqual(mismatches, out.count / 20,
                                 "\(mismatches)/\(out.count) cells disagree with OpenCV")
    }

    func testSeedCellsAlwaysLabelThemselves() {
        let seed = makeSeedIds()
        let out = NearestLabel.label(seedIds: seed, grid: grid)
        for i in 0..<seed.count where seed[i] != 0 {
            XCTAssertEqual(out[i], seed[i], "seed cell \(i) must be labeled with its own id")
        }
    }

    func testNoSeedsReturnsAllZero() {
        let seed = [Int32](repeating: 0, count: grid.width * grid.height)
        let out = NearestLabel.label(seedIds: seed, grid: grid)
        XCTAssertTrue(out.allSatisfy { $0 == 0 })
    }
}
