import XCTest
@testable import AmodalRoadKit

/// Golden values generated by the REAL `instances.occluder_instance_ids`
/// (see GoldenData_OccluderInstances.swift's header), not just Swift
/// self-consistency. The 100x60 synthetic scene exercises: a detection
/// exactly claiming a vehicle blob (source "instance"), a leftover
/// undetected blob big enough to survive on its own (source "blob"), a
/// too-small leftover sliver that must be dropped (left at id 0), a person
/// blob that does NOT touch the road and must not appear as any instance,
/// and renumbering by descending pixel area.
final class OccluderInstancesGoldenValueTests: XCTestCase {
    let width = 100
    let height = 60

    func testMatchesPython() {
        let sem = GoldenData.occluderInstancesSem
        let detA = OccluderDetection(label: "vehicle", score: 0.9,
                                     mask: Self.rectMask(x0: 10, y0: 20, x1: 26, y1: 36, width: width, height: height),
                                     isVehicle: true)
        let detB = OccluderDetection(label: "vehicle", score: 0.4,
                                     mask: Self.rectMask(x0: 50, y0: 15, x1: 66, y1: 28, width: width, height: height),
                                     isVehicle: true)

        let (instIds, instances) = OccluderInstances.occluderInstanceIds(
            semLabels: sem, detections: [detA, detB], width: width, height: height)

        XCTAssertEqual(instIds, GoldenData.occluderInstancesInstIds)

        XCTAssertEqual(instances.count, 3)
        XCTAssertEqual(instances[0], VehicleInstance(
            instId: 1, label: "vehicle", score: .nan, pixelArea: 300,
            centroidU: 79, centroidV: 22, bboxU0: 70, bboxV0: 15, bboxU1: 90, bboxV1: 30,
            selectable: true, source: "blob"))
        XCTAssertEqual(instances[1], VehicleInstance(
            instId: 2, label: "vehicle", score: 0.9, pixelArea: 256,
            centroidU: 17, centroidV: 27, bboxU0: 10, bboxV0: 20, bboxU1: 26, bboxV1: 36,
            selectable: true, source: "instance"))
        XCTAssertEqual(instances[2], VehicleInstance(
            instId: 3, label: "vehicle", score: 0.4, pixelArea: 208,
            centroidU: 57, centroidV: 21, bboxU0: 50, bboxV0: 15, bboxU1: 66, bboxV1: 28,
            selectable: true, source: "instance"))
    }

    private static func rectMask(x0: Int, y0: Int, x1: Int, y1: Int, width: Int, height: Int) -> [Bool] {
        var mask = [Bool](repeating: false, count: width * height)
        for y in y0..<y1 {
            for x in x0..<x1 {
                mask[y * width + x] = true
            }
        }
        return mask
    }
}

extension VehicleInstance: Equatable {
    /// `score` is `.nan` for "blob"-source instances (matching Python's
    /// `float("nan")`), so a plain synthesized `==` (NaN != NaN) would make
    /// every "blob" instance compare unequal to itself -- this treats two
    /// NaN scores as equal so XCTAssertEqual works the way a human reading
    /// the test expects. Conformance lives here (test-only) rather than on
    /// the type itself since production code never needs to compare two
    /// `VehicleInstance` values for equality.
    public static func == (lhs: VehicleInstance, rhs: VehicleInstance) -> Bool {
        let scoresEqual = (lhs.score.isNaN && rhs.score.isNaN) || lhs.score == rhs.score
        return lhs.instId == rhs.instId && lhs.label == rhs.label && scoresEqual
            && lhs.pixelArea == rhs.pixelArea && lhs.centroidU == rhs.centroidU && lhs.centroidV == rhs.centroidV
            && lhs.bboxU0 == rhs.bboxU0 && lhs.bboxV0 == rhs.bboxV0 && lhs.bboxU1 == rhs.bboxU1 && lhs.bboxV1 == rhs.bboxV1
            && lhs.selectable == rhs.selectable && lhs.source == rhs.source
    }
}
