import XCTest
import simd
@testable import AmodalRoadKit

/// Golden values generated by the REAL `bev.warp_to_bev` (src/bev.py) via
/// `cv2.warpPerspective`, on a 720x1280 synthetic source with two
/// rectangular regions -- not just Swift self-consistency. See
/// GoldenValueTests.swift's header for the overall approach.
final class WarpGoldenValueTests: XCTestCase {
    let grid = BevGrid(ppm: 2.0, xMin: -5.0, xMax: 5.0, zMin: 0.5, zMax: 15.0)
    let srcW = 1280
    let srcH = 720

    /// H = bev.homography_bev_to_image(K, n, grid) for the same fixture as
    /// GoldenValueTests -- but note this is a DIFFERENT grid (ppm=2, not 20),
    /// so it is not the same H as that file's `n`/`K`/`grid` combination.
    var H: simd_double3x3 {
        simd_double3x3(
            SIMD3(400.0, -24.24242424242424, 0.0),
            SIMD3(-320.0, -228.48484848484847, -0.5),
            SIMD3(5640.0, 8302.672125033798, 14.75)
        )
    }

    func makeBoolSource() -> [Bool] {
        var src = [Bool](repeating: false, count: srcW * srcH)
        for y in 560..<680 {
            for x in 200..<1000 {
                src[y * srcW + x] = true
            }
        }
        return src
    }

    func makeFloatSource() -> [Float] {
        var src = [Float](repeating: 0, count: srcW * srcH)
        for y in 560..<680 {
            for x in 200..<1000 {
                src[y * srcW + x] = 1.0
            }
        }
        for y in 600..<650 {
            for x in 400..<700 {
                src[y * srcW + x] = 0.5
            }
        }
        return src
    }

    func testNearestMatchesOpenCV() {
        let src = makeBoolSource()
        let out = Warp.warpToBev(mask: src, srcWidth: srcW, srcHeight: srcH, H: H, grid: grid)
        XCTAssertEqual(out.count, grid.width * grid.height)

        let expectedFlat = GoldenData.warpNearestFlat
        XCTAssertEqual(expectedFlat.count, out.count)

        // Exact agreement, not just "close": measured zero mismatches against
        // real cv2.warpPerspective output on this fixture (including cells
        // right at the source rectangle's edge, where nearest-neighbour
        // tie-breaking could plausibly have differed) -- pythonRound's
        // round-half-to-even matches cv2's rounding closely enough that
        // there's no boundary slop to allow for here.
        for i in 0..<out.count {
            XCTAssertEqual(out[i], expectedFlat[i] == 1, "cell \(i)")
        }
    }

    func testBilinearMatchesOpenCV() {
        let src = makeFloatSource()
        let out = Warp.warpToBev(src: src, srcWidth: srcW, srcHeight: srcH,
                                 H: H, grid: grid, interpolation: .bilinear)
        let expected = GoldenData.warpLinearFlat
        XCTAssertEqual(expected.count, out.count)
        for i in 0..<out.count {
            XCTAssertEqual(Double(out[i]), expected[i], accuracy: 1e-3, "cell \(i)")
        }
    }
}
