import XCTest
@testable import AmodalRoadKit

/// Golden values generated by the REAL `disturbance.width_disturbance`
/// (src/disturbance.py) on a 40x25 synthetic BEV: three road-width bands
/// (3.0m usable, 0.5m too-narrow/excluded, 4.0m usable), two vehicles with
/// occluded cells spanning both usable bands, and a third vehicle with NO
/// occluded cells at all (exercises the "no usable rows" -> all-zero/nil
/// result path).
final class WidthDisturbanceGoldenValueTests: XCTestCase {
    let grid = BevGrid(ppm: 10.0, xMin: -2.0, xMax: 2.0, zMin: 0.5, zMax: 3.0)

    func testMatchesPython() {
        XCTAssertEqual(grid.width, 40)
        XCTAssertEqual(grid.height, 25)

        var amodalBev = [Bool](repeating: false, count: grid.width * grid.height)
        for y in 0..<10 { for x in 5..<35 { amodalBev[y * grid.width + x] = true } }    // span 3.0m, usable
        for y in 10..<15 { for x in 10..<15 { amodalBev[y * grid.width + x] = true } }  // span 0.5m, NOT usable
        for y in 15..<25 { for x in 0..<40 { amodalBev[y * grid.width + x] = true } }   // span 4.0m, usable

        var occludedBev = [Bool](repeating: false, count: grid.width * grid.height)
        for y in 2..<8 { for x in 6..<12 { occludedBev[y * grid.width + x] = true } }
        for y in 3..<7 { for x in 22..<30 { occludedBev[y * grid.width + x] = true } }
        for y in 11..<13 { for x in 11..<13 { occludedBev[y * grid.width + x] = true } } // in the excluded band
        for y in 18..<20 { for x in 5..<9 { occludedBev[y * grid.width + x] = true } }

        var instBev = [Int32](repeating: 0, count: grid.width * grid.height)
        for y in 0..<10 { for x in 0..<15 { instBev[y * grid.width + x] = 1 } }
        for y in 0..<10 { for x in 20..<35 { instBev[y * grid.width + x] = 2 } }
        for y in 15..<25 { for x in 0..<15 { instBev[y * grid.width + x] = 1 } }

        let vehicles = (1...3).map { id in
            VehicleInstance(instId: Int32(id), label: "vehicle", score: 0.9, pixelArea: 100,
                            centroidU: 0, centroidV: 0, bboxU0: 0, bboxV0: 0, bboxU1: 1, bboxV1: 1,
                            selectable: true, source: "instance")
        }

        let (perVehicle, total) = WidthDisturbance.measure(
            amodalBev: amodalBev, occludedBev: occludedBev, instBev: instBev, vehicles: vehicles, grid: grid)

        let m1 = perVehicle[1]!
        XCTAssertEqual(m1.widthMaxPct, 20.0, accuracy: 1e-9)
        XCTAssertEqual(m1.widthMeanPct, 17.5, accuracy: 1e-9)
        XCTAssertEqual(m1.widthMaxM, 0.6, accuracy: 1e-9)
        XCTAssertEqual(m1.widthRoadMAtMax, 3.0, accuracy: 1e-9)
        XCTAssertEqual(m1.widthMaxAtZM ?? -1, 2.75, accuracy: 1e-9)

        let m2 = perVehicle[2]!
        XCTAssertEqual(m2.widthMaxPct, 26.67, accuracy: 1e-9)
        XCTAssertEqual(m2.widthMeanPct, 26.67, accuracy: 1e-9)
        XCTAssertEqual(m2.widthMaxM, 0.8, accuracy: 1e-9)
        XCTAssertEqual(m2.widthRoadMAtMax, 3.0, accuracy: 1e-9)
        XCTAssertEqual(m2.widthMaxAtZM ?? -1, 2.65, accuracy: 1e-9)

        let m3 = perVehicle[3]!
        XCTAssertEqual(m3.widthMaxPct, 0.0)
        XCTAssertEqual(m3.widthMeanPct, 0.0)
        XCTAssertEqual(m3.widthMaxM, 0.0)
        XCTAssertEqual(m3.widthRoadMAtMax, 0.0)
        XCTAssertNil(m3.widthMaxAtZM)

        XCTAssertEqual(total.widthMaxPct, 46.67, accuracy: 1e-9)
        XCTAssertEqual(total.widthMeanPct, 30.83, accuracy: 1e-9)
        XCTAssertEqual(total.widthMaxM, 1.4, accuracy: 1e-9)
        XCTAssertEqual(total.widthRoadMAtMax, 3.0, accuracy: 1e-9)
        XCTAssertEqual(total.widthMaxAtZM ?? -1, 2.65, accuracy: 1e-9)
    }
}
